const DefinitionsActionTypes = {
    OPEN_DEFINITIONS_MODAL: 'OPEN_DEFINITIONS_MODAL',
    CLOSE_DEFINITIONS_MODAL: 'CLOSE_DEFINITIONS_MODAL',
    UPDATE_DEFINITIONS_NUMLINES: 'UPDATE_DEFINITIONS_NUMLINES',
    UPDATE_DEFINITIONS_TEXT: 'UPDATE_DEFINITIONS_TEXT',
    RESET_DEFINITIONS_MODAL: 'RESET_DEFINITIONS_MODAL',
    UPDATE_DEFINITIONS_EXTRASPACE: 'UPDATE_DEFINITIONS_EXTRASPACE'
}

export default DefinitionsActionTypes;