const FillGapsActionTypes = {
    OPEN_FILLWORDS_MODAL: 'OPEN_FILLWORDS_MODAL',
    CLOSE_FILLWORDS_MODAL: 'CLOSE_FILLWORDS_MODAL',
    UPDATE_FILLWORDS_TEXT: 'UPDATE_FILLWORDS_TEXT',
    UPDATE_FILLWORDS_ADDHOWTOSOLVE: 'UPDATE_FILLWORDS_ADDHOWTOSOLVE',
    RESET_FILLWORDS: 'RESET_FILLWORDS',
    UPDATE_FILLWORDS_MODE: 'UPDATE_FILLWORDS_MODE',
    UPDATE_FILLWORDS_TEXTSELECTION: 'UPDATE_FILLWORDS_TEXTSELECTION',
    UPDATE_FILLWORDS_ADDSELECTED: 'UPDATE_FILLWORDS_ADDSELECTED',
    UPDATE_FILLWORDS_DELETESELECTED: 'UPDATE_FILLWORDS_DELETESELECTED',
}

export default FillGapsActionTypes;