const DefinitionsDevelopActionTypes = {
    OPEN_DEFINITIONS_DEVELOP_MODAL: 'OPEN_DEFINITIONS_DEVELOP_MODAL',
    CLOSE_DEFINITIONS_DEVELOP_MODAL: 'CLOSE_DEFINITIONS_DEVELOP_MODAL',
    UPDATE_SELECTED_EXERCISE: 'UPDATE_SELECTED_EXERCISE',
    RESET_DEFINITIONS_DEVELOP_MODAL: 'RESET_DEFINITIONS_DEVELOP_MODAL',
}

export default DefinitionsDevelopActionTypes;