const WordSearchActionTypes = {
    /*SEARCH_PICTOGRAMS: 'SEARCH_PICTOGRAMS',
    ADD_PICTOGRAM: 'ADD_PICTOGRAM',
    FETCH_PICTOGRAMS_SUCCESS: 'FETCH_PICTOGRAMS_SUCCESS',*/
    OPEN_WORDSEARCH_MODAL: 'OPEN_WORDSEARCH_MODAL',
    CLOSE_WORDSEARCH_MODAL: 'CLOSE_WORDSEARCH_MODAL',
    UPDATE_WORDSEARCH_ROWS: 'UPDATE_WORDSEARCH_ROWS',
    UPDATE_WORDSEARCH_COLS: 'UPDATE_WORDSEARCH_COLS',
    UPDATE_WORDSEARCH_DICTIONARY: 'UPDATE_WORDSEARCH_DICTIONARY',
    UPDATE_WORDSEARCH_VERTICAL: 'UPDATE_WORDSEARCH_VERTICAL',
    UPDATE_WORDSEARCH_HORIZONTAL: 'UPDATE_WORDSEARCH_HORIZONTAL',
    UPDATE_WORDSEARCH_DIAGONAL: 'UPDATE_WORDSEARCH_DIAGONAL',
    UPDATE_WORDSEARCH_MAXWORDS: 'UPDATE_WORDSEARCH_MAXWORDS',
    UPDATE_WORDSEARCH_DIACRITICS: 'UPDATE_WORDSEARCH_DIACRITICS',
    UPDATE_WORDSEARCH_ACTIVATEBACKWARDS: 'UPDATE_WORDSEARCH_ACTIVATEBACKWARDS',
    UPDATE_WORDSEARCH_BACKWARDSPROBABILITY: 'UPDATE_WORDSEARCH_BACKWARDSPROBABILITY',
    UPDATE_WORDSEARCH_ERROR: 'UPDATE_WORDSEARCH_ERROR',
    RESET_WORDSEARCH: 'RESET_WORDSEARCH',
    CREATE_WORDSEARCH: 'CREATE_WORDSEARCH',
}

export default WordSearchActionTypes;