const WordSearchActionTypes = {
    OPEN_WORDSEARCH_MODAL: 'OPEN_WORDSEARCH_MODAL',
    CLOSE_WORDSEARCH_MODAL: 'CLOSE_WORDSEARCH_MODAL',
    UPDATE_WORDSEARCH_ROWS: 'UPDATE_WORDSEARCH_ROWS',
    UPDATE_WORDSEARCH_COLS: 'UPDATE_WORDSEARCH_COLS',
    UPDATE_WORDSEARCH_DICTIONARY: 'UPDATE_WORDSEARCH_DICTIONARY',
    UPDATE_WORDSEARCH_VERTICAL: 'UPDATE_WORDSEARCH_VERTICAL',
    UPDATE_WORDSEARCH_HORIZONTAL: 'UPDATE_WORDSEARCH_HORIZONTAL',
    UPDATE_WORDSEARCH_DIAGONAL: 'UPDATE_WORDSEARCH_DIAGONAL',
    UPDATE_WORDSEARCH_MAXWORDS: 'UPDATE_WORDSEARCH_MAXWORDS',
    UPDATE_WORDSEARCH_ACTIVATEBACKWARDS: 'UPDATE_WORDSEARCH_ACTIVATEBACKWARDS',
    UPDATE_WORDSEARCH_BACKWARDSPROBABILITY: 'UPDATE_WORDSEARCH_BACKWARDSPROBABILITY',
    UPDATE_WORDSEARCH_ERROR: 'UPDATE_WORDSEARCH_ERROR',
    RESET_WORDSEARCH: 'RESET_WORDSEARCH',
    CREATE_WORDSEARCH: 'CREATE_WORDSEARCH',
    UPDATE_WORDSEARCH_READY: 'UPDATE_WORDSEARCH_READY',
    UPDATE_WORDSEARCH_HIDDENWORDS: 'UPDATE_WORDSEARCH_HIDDENWORDS',
    UPDATE_WORDSEARCH_READYTOCREATE: 'UPDATE_WORDSEARCH_READYTOCREATE',
    UPDATE_WORDSEARCH_WORDS: 'UPDATE_WORDSEARCH_WORDS'
}

export default WordSearchActionTypes;