const WordSearchActionTypes = {
    SEARCH_PICTOGRAMS: 'SEARCH_PICTOGRAMS',
    ADD_PICTOGRAM: 'ADD_PICTOGRAM',
    FETCH_PICTOGRAMS_SUCCESS: 'FETCH_PICTOGRAMS_SUCCESS',
    OPEN_WORDSEARCH_MODAL: 'OPEN_WORDSEARCH_MODAL',
    CLOSE_WORDSEARCH_MODAL: 'CLOSE_WORDSEARCH_MODAL'
}

export default WordSearchActionTypes;