const TrueFalseActionTypes = {
    OPEN_TRUEFALSE_MODAL: 'OPEN_TRUEFALSE_MODAL',
    UPDATE_TRUEFALSE_TEXT: 'UPDATE_TRUEFALSE_TEXT',
    RESET_TRUEFALSE_MODAL: 'RESET_TRUEFALSE_MODAL',
    CLOSE_TRUEFALSE_MODAL: 'CLOSE_TRUEFALSE_MODAL'
    }

export default TrueFalseActionTypes;